name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # main 브랜치에 푸시될 때 작동
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          
      - run: flutter build web --release --base-href "/globalcurrencyviewer/"
      
      # 💡 [핵심 수정] SEO 및 인증 관련 파일들을 빌드 폴더로 모두 강제 복사
      - name: Copy SEO and Verification Files
        run: |
          cp web/google0a74ca61ce6611d3.html build/web/
          cp web/sitemap.xml build/web/
          cp web/robots.txt build/web/
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # 빌드된 결과물이 있는 폴더
          branch: gh-pages # 배포용 브랜치
